print("Welcome to the tip calculator!")
bill = float(input("What is the total bill?  $"))
tip = float(input("How much would you like to tip? %"))
tip_fraction = float(tip/100)
tip_in_value = float(tip_fraction * bill)
total_to_pay = float(tip_in_value + bill)
people_splitting_bill = float(input("How many people to split the bill? "))
one_person_pay = float(total_to_pay/people_splitting_bill)

print(f"Each person should pay: ${one_person_pay}")